CREATE TABLE IF NOT EXISTS categories (
  id CHAR(36) PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  color VARCHAR(7) DEFAULT '#3498db',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);